import type { BillState } from "./types";

export const SEED: BillState = {
  selectedId: "inv-1",
  business: {
    name: "Aarohi Studio",
    gstin: "19AAPCA3182R1Z7",
    pan: "AAPCA3182R",
    address: "12/3 Gariahat Road, Ballygunge\nKolkata 700019",
    state: "West Bengal",
    email: "hello@aarohistudio.in",
    phone: "+91 98300 11220",
    bankName: "HDFC Bank, Gariahat",
    accountNumber: "50100123456789",
    ifsc: "HDFC0001234",
    documentTitle: "Tax Invoice",
    numberPrefix: "CB",
    footerNote: "This is a computer-generated document.",
  },
  clients: [
    {
      id: "cl-1",
      name: "Bistro Forty Two",
      gstin: "19AABCB4412F1Z3",
      address: "42 Park Street\nKolkata 700016",
      state: "West Bengal",
      email: "accounts@bistro42.in",
      phone: "+91 33 4001 4242",
    },
    {
      id: "cl-2",
      name: "Northline Apparel",
      gstin: "27AADCN9088Q1Z5",
      address: "Andheri East, MIDC\nMumbai 400093",
      state: "Maharashtra",
      email: "ops@northline.co",
      phone: "+91 22 6120 8800",
    },
  ],
  invoices: [
    {
      id: "inv-1",
      number: "CB-2026-0001",
      date: "2026-09-02",
      dueDate: "2026-09-16",
      status: "paid",
      clientId: "cl-1",
      gstMode: "intra",
      placeOfSupply: "West Bengal",
      reverseCharge: false,
      notes: "Thank you for the repeat brief. Payment received via NEFT.",
      items: [
        {
          id: "li-1",
          description: "Brand kit — logo, colour, type, 8 social templates",
          hsn: "998361",
          qty: 1,
          rate: 18000,
          gstRate: 18,
        },
        {
          id: "li-2",
          description: "Instagram carousel set (12 posts)",
          hsn: "998361",
          qty: 12,
          rate: 650,
          gstRate: 18,
        },
      ],
    },
    {
      id: "inv-2",
      number: "CB-2026-0002",
      date: "2026-09-08",
      dueDate: "2026-09-22",
      status: "unpaid",
      clientId: "cl-2",
      gstMode: "inter",
      placeOfSupply: "Maharashtra",
      reverseCharge: false,
      notes: "45s product film, colour grade included. 50% already billed as advance.",
      items: [
        {
          id: "li-3",
          description: "Product film edit & grade (45 seconds)",
          hsn: "998364",
          qty: 1,
          rate: 24000,
          gstRate: 18,
        },
      ],
    },
    {
      id: "inv-3",
      number: "CB-2026-0003",
      date: "2026-09-11",
      dueDate: "2026-09-25",
      status: "draft",
      clientId: "cl-1",
      gstMode: "intra",
      placeOfSupply: "West Bengal",
      reverseCharge: false,
      notes: "",
      items: [
        {
          id: "li-4",
          description: "Monthly content retainership — September",
          hsn: "998361",
          qty: 1,
          rate: 12000,
          gstRate: 18,
        },
      ],
    },
  ],
};
